// CLIPS Grammar Definition
// This grammar is based on the CLIPS Reference Manual and is structured
// to align with the provided Java parser implementation.

{
  // Meta-information for parser generators like Grammar-Kit
  parserClass="is.yarr.clips.parser.CLIPSParser"
  psiClassPrefix="CLIPS"
  psiImplClassSuffix="Impl"
  psiPackage="is.yarr.clips.psi"
  psiImplPackage="is.yarr.clips.psi.impl"

  elementTypeHolderClass="is.yarr.clips.psi.CLIPSElementTypes"
  elementTypeClass="is.yarr.clips.psi.CLIPSElementType"
  tokenTypeClass="is.yarr.clips.psi.CLIPSTokenType"

  // Make comments and whitespace non-significant for the grammar rules
  extends(".*")="is.yarr.clips.psi.impl.CLIPSPsiElementImpl"
  implements("parameter|variable_element|global_variable_def|def_name|(.*_construct)")="is.yarr.clips.psi.CLIPSNamedElement"

  tokens=[
    KEYWORD="KEYWORD"
    BUILTIN_FUNCTION="BUILTIN_FUNCTION"
  ]
}

// The root of a CLIPS file is a sequence of constructs or function calls.
File ::= item*

private item ::= construct | function_call | COMMENT

// ----------- Basic Types & Expressions -----------
// These correspond to tokens from CLIPSLexer.flex and CLIPSTypes.java
constant ::= STRING | NUMBER | IDENTIFIER | "crlf" | "t" | "TRUE" | "FALSE" | "nil"
variable_element ::= VARIABLE | GLOBAL_VARIABLE | MULTIFIELD_VARIABLE

def_name ::= IDENTIFIER  // The name of some construct def*

expression ::= constant | variable_element | function_call

// A function call is a parenthesized list with a function name followed by zero or more expressions
// A function call can be a special control structure like 'if' or a regular call.
// The parser will check for the 'if' keyword first to resolve the ambiguity.
function_call ::= LPAREN (if_guts | regular_function_guts) RPAREN

// The body of an if-then-else construct.
// Syntax: (if <expression> then <action>* [else <action>*])
private if_guts ::= "if" expression "then" expression* ("else" expression*)? {
  pin=1 // Pin after the 'if' keyword to commit to this parsing rule.
}

// The body of a regular function call.
private regular_function_guts ::= function_name expression*

// A function name can be an identifier, a built-in, a variable, or a keyword.
// Keywords like 'and', 'or', 'not' are parsed here. The 'if' keyword is
// handled by the 'if_guts' rule because of the ordered choice in the 'function_call' rule.
private function_name ::= def_name | BUILTIN_FUNCTION | variable_element | KEYWORD


//private function_name ::= IDENTIFIER | BUILTIN_FUNCTION | variable_element

// ----------- Top-Level Constructs -----------
construct ::= defrule_construct
            | deftemplate_construct
            | deffacts_construct
            | defglobal_construct
            | deffunction_construct
            | defmodule_construct
            | defclass_construct


// ----------- Deftemplate Construct -----------
// Based on <deftemplate-construct> from the CLIPS Reference Manual [1]
deftemplate_construct ::= LPAREN "deftemplate" def_name (COMMENT)? slot_definition* RPAREN {
    pin=2 // Pin 'deftemplate' keyword to aid parser recovery
}

slot_definition ::= single_slot_definition | multislot_definition

single_slot_definition ::= LPAREN "slot" def_name template_attribute* RPAREN {
    pin=2
}

multislot_definition ::= LPAREN "multislot" def_name template_attribute* RPAREN {
    pin=2
}

// A slot can have one or more attributes.
template_attribute ::= constraint_attribute | default_attribute

// --- Constraint Attributes ---
// Based on CLIPS Reference Manual, Section 11
constraint_attribute ::= type_constraint
                       | range_constraint
                       | cardinality_constraint

type_constraint ::= LPAREN "type" type_specifier+ RPAREN {
    pin=2
}

// A type specifier is a CLIPS type name (e.g., STRING, INTEGER) or a variable.
type_specifier ::= IDENTIFIER | VARIABLE

range_constraint ::= LPAREN "range" range_specification range_specification RPAREN {
    pin=2
}

range_specification ::= NUMBER | VARIABLE

cardinality_constraint ::= LPAREN "cardinality" cardinality_specification cardinality_specification RPAREN {
    pin=2
}

cardinality_specification ::= NUMBER | VARIABLE

// --- Default Attribute ---
// Based on CLIPS Reference Manual, Appendix G
default_attribute ::= LPAREN "default" expression* RPAREN
                    | LPAREN "default-dynamic" expression* RPAREN

// ----------- Defrule Construct -----------
// Based on <defrule-construct> from the CLIPS Reference Manual [1]
defrule_construct ::= LPAREN "defrule" IDENTIFIER [STRING]
                        [declaration]
                        conditional_element*
                        "=>"
                        action*
                      RPAREN

private declaration ::= LPAREN "declare" rule_property+ RPAREN
private rule_property ::= LPAREN "salience" NUMBER RPAREN // Simplified

private conditional_element ::= pattern_ce | test_ce // Simplified, others include and, or, not, etc. [1]
private pattern_ce ::= LPAREN def_name expression* RPAREN // Simplified pattern
private test_ce ::= LPAREN "test" expression RPAREN
private action ::= expression

// ----------- Other Constructs -----------
deffacts_construct ::= LPAREN "deffacts" IDENTIFIER [STRING] deffacts_rhs_pattern* RPAREN
deffacts_rhs_pattern ::= LPAREN def_name expression* RPAREN

deffunction_construct ::= LPAREN "deffunction" IDENTIFIER [STRING]
                            LPAREN parameter_list [MULTIFIELD_VARIABLE] RPAREN
                            action*
                          RPAREN
parameter ::= VARIABLE
parameter_list ::= parameter*

defglobal_construct ::= LPAREN "defglobal" [IDENTIFIER] defglobal_assignment* RPAREN
global_variable_def ::= GLOBAL_VARIABLE
private defglobal_assignment ::= global_variable_def "=" expression

defmodule_construct ::= LPAREN "defmodule" def_name comment? port_specification* RPAREN

private port_specification ::= LPAREN (import_spec | export_spec) RPAREN

import_spec ::= "import" def_name port_item
export_spec ::= "export" port_item

// A port item can be a wildcard (?ALL, ?NONE), or a construct type followed by a wildcard or one or more names.
private port_item ::= variable_element | (port_construct_type (variable_element | def_name+))

// The types of constructs that can be imported/exported.
private port_construct_type ::= "deftemplate" | "defclass" | "defglobal" | "deffunction" | "defgeneric"


defclass_construct ::= LPAREN "defclass" IDENTIFIER [STRING]
                         ["is-a" def_name+]
                         slot_definition*
                       RPAREN